### ISSUE TITLE
Doesn't work no Alpine Linux 3.7

### ISSUE THREAD

**Issue by godontop** [brbsix/pip-utils#4]
When I execute "!pip3-utils locate /usr/bin/jupyter" in Jupyter notebook, return nothing.
![pip-utils](https://user-images.githubusercontent.com/9638177/35688632-8f18d9ea-07ac-11e8-86ce-791960a4a570.png)

**Comment by brbsix** [comment]
I spun up a Docker container running Alpine and the following seems to work:

    / # PYTHONNOUSERSITE=1 pip3-utils locate /usr/bin/jupyter
    jupyter-core

Writing this app, I made the assumption to interact with packages installed to the user site by default (if it's enabled). At least for my use cases, packages are generally installed in a virtualenv or with pip's `--user` option. However that is obviously not the case here as packages are being installed globally as root.
